### ISSUE TITLE
Authorization error in parse "user profile"

### ISSUE THREAD

**Issue by steinhae** [ghaiklor/passport-soundcloud-token#82]
I tried to set up this module and it didn't work. I would receive the following error with every request:

```
name: 'InternalOAuthError',
  message: 'Failed to fetch user profile',
  oauthError: { statusCode: 401, data: '' } }
```

The error occurs because the access token is being send in the header as a bearer token which is not supported by Soundcloud (https://developers.soundcloud.com/docs/api/reference#comments).

I use this little workaround to pass the access token as an url parameter.
(index.js :110)
`this._oauth2.get(this._profileURL + "?oauth_token=" + accessToken, accessToken, function (error, body, res) {`

Fixes the error for me.

**Comment by ghaiklor** [comment]
@zeddsdead great, thanks for your update. Can you make a PR with the fix?

**Comment by steinhae** [comment]
@ghaiklor done! Thanks for creating this module :)
Btw. found a very simple solution.

**Comment by ghaiklor** [comment]
@zeddsdead published under minor update
